# Generated by Django 4.1 on 2025-06-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id_aeropuerto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_a', models.CharField(max_length=100)),
                ('direccion_a', models.CharField(max_length=200)),
                ('ciudad_a', models.CharField(max_length=100)),
                ('pais_a', models.CharField(max_length=100)),
                ('num_pista', models.IntegerField()),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
    ]
